name: myHttpTriggerFunction Deployment

on:
  workflow_dispatch:
    inputs:
      restrict:
        description: Restrict workflow to only run when triggered by me
        required: true
        default: true
      environment:
        description: Production Environment
        required: true
        default: 'production'
        

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Whom can trigger this workflow.
    if: github.actor == 'angelllopez'
    #if: contains(github.event.sender.roles, 'admin')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Azure CLI
        uses: azure/login@v1

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          tenant: '${{ secrets.AZURE_TENANT_ID }}'
          client-id: '${{ secrets.AZURE_CLIENT_ID }}'
          app-name: myHttpTriggerFunction
          publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE }}
